### ISSUE TITLE
Discord WebHook Error

### ISSUE THREAD

**Issue by kiliasu** [atomicptr/hoyo-daily-logins-helper#10]
My automatic check-in function is working fine. I'm using a configuration file to operate it and have enabled the scheduled mode. However, it seems that my webhook is not functioning properly. I will attach a screenshot below.
![屏幕截图 2023-06-06 093920](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/131132749/b3ac967a-7d21-4453-bcc6-f18a4580785c)
![屏幕截图 2023-06-06 094456](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/131132749/89be330b-ce56-46b8-a062-940f140284de)

**Comment by atomicptr** [comment]
I tested the webhook url and it seems correct and then noticed the actual mistake :)... notifications should be under \[config\] and not \[\[accounts\]\]

**Comment by kiliasu** [comment]
I changed the position of the webhook URL in the configuration file, placing it under the [config] section. It seems to be fine, but today, despite having already checked in, Discord did not receive any notifications. Is this perhaps not designed to work this way, or is there still an issue? Also, thank you for your help！

**Comment by atomicptr** [comment]
It will only send the discord notification  when an error happens or if it actually checks in so already checked in won't generate one.

**Comment by kiliasu** [comment]
Just wanted to say thanks again for all your help. I really appreciate it!
