### ISSUE TITLE
Erron discord web hook 

### ISSUE THREAD

**Issue by tathaha** [atomicptr/hoyo-daily-logins-helper#15]
![image](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/77224364/7bb43c2a-c345-47ff-a231-1645cdb85586)
this erron make me anoying

**Comment by tathaha** [comment]
it have after i add the nofication
![image](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/77224364/6453f901-aed2-46e8-966e-7b07a3e438b3)

**Comment by atomicptr** [comment]
Can you check what the end of that line looks like? This error sounds a bit like there is a syntax error in the TOML file

**Comment by tathaha** [comment]
i fix it but it does notify me 
![image](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/77224364/622c5a11-e597-4ec0-9124-a9ac64407a89)

**Comment by atomicptr** [comment]
Well what does the program say in the logs? Did you already checkin today?  It only notifies you when a new checkin happens or if there was an error not for the "already checked in today"

**Comment by tathaha** [comment]
Ok thank
