### ISSUE TITLE
some thoughts

### ISSUE THREAD

**Issue by NullIndent** [atomicptr/hoyo-daily-logins-helper#4]
Reduce the size of the docker image
Multi-platform docker image
Multi-account and multi-game checkin
Daily timed automatic checkin

function will be more complete

**Comment by atomicptr** [comment]
With v2.0.0, I added multi account support (see updated README.md) and reduced the size of the docker image (by running the software in python:3.11-slim)

I haven't really looked into multi platform docker images at all, presumably you'd want to run this on ARM or something right?

With daily timed automatic check-in times I presume you mean this software running as a sort of service and doing this automatically? I consider this currently to be out of scope and would recommend running this via cron (which is what I'm doing).

**Comment by atomicptr** [comment]
I created a new ticket for that idea specifically #6
