### ISSUE TITLE
Add discord webhook api

### ISSUE THREAD

**Issue by djdoolky76** [atomicptr/hoyo-daily-logins-helper#5]
Can you add Discord webhook API? for notification purposes if auto check-in goes well in multiple accounts even on a single acc.

**Comment by atomicptr** [comment]
Not quite sure if there is much point in doing this, do you want to see what you got? Or when reset happened?

**Comment by atomicptr** [comment]
Added with 2.3.0, see  https://github.com/atomicptr/hoyo-daily-logins-helper#discord-notifications
