### ISSUE TITLE
Perhaps add library functionality?

### ISSUE THREAD

**Issue by moveonwasd** [atomicptr/hoyo-daily-logins-helper#8]
I want to create a bot but script interface seems unsuitable for this
I would need to run this in a docker with script that could run this via CLI for every account on a schedule (even though there is scheduler built in, there is no way (if I correctly understood how it works) I can add new accounts while it executes), and then I would need to read terminal for results
It would be much easier to just call something like claim_reward(game, cookie, language, etc) from my bot script. Even better would be functionality to run_scheduler() with the ability to add_new_account() on the fly. And even better will it be to pass a function to run_scheduler() as an argument, which will be called from your script with claiming reward results for each account.

I know, it sounds like I just want someone to implement features for me, but IMO most of described is must-have for this type of project and would be useful for many people. I was a little surprised to find out that it's not a library, but a CLI program.

**Comment by atomicptr** [comment]
First and foremost: This is a CLI program and doesn't aim to be anything else. For your use-case, I found a library recently that also offers this type of functionality: https://thesadru.github.io/genshin.py/daily_rewards/ 

Technically you could import this as a library (although the package name would probably be src now that I think about it...) as the function that performs the checkin is available from the games sub-package. Alternatively you could also obviously just copy the file and adjust it to your needs, the process of claiming rewards in itself is very trivial :)
