### ISSUE TITLE
Configuration file error

### ISSUE THREAD

**Issue by yagyeshgod** [atomicptr/hoyo-daily-logins-helper#9]
Hey I was able to implement this using single commands but config file is not working.I am definitely doing sometihing wrong.  Can u check.. I am attaching image.

![Screenshot (240)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/00434f23-3ada-4136-92c3-1ce3a85b799a)

Also when i try to run container in docker it exits immediately.

**Comment by atomicptr** [comment]
Your docker file seems up to date but the other thing seems installed via pip seems outdated.

If you run the cli like this:

```
$ hoyo-daily-logins-helper --genshin -c test 
```

This should print the version.

How are you using the docker command if it's closing immediately?

**Comment by yagyeshgod** [comment]
1. Yes pipx version is showing 1.2.3. How to update this to latest version? 

![Screenshot (243)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/27f9a1e6-3ac6-41d3-bd66-68ff398365ef)

2. I was trying to run container with docker desktop but it exits immediately. What steps am  I missing? 

![Screenshot (249)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/033707f4-1bb7-479e-938f-aedd7f467a93)

Thanks

**Comment by atomicptr** [comment]
1. Just do this:
```bash
$ pipx upgrade hoyo-daily-logins-helper
```

2. But how are you running this? Without arguments/configuration? That will obviously not work, if you just want to run it you might want to set environment variables like:

HOYO\_GAME=genshin
HOYO\_COOKIE=....

then it should at least attempt that login (there should also be a log somewhere).

If you want to use a config file with Docker you need to map it into the container and use HOYO_CONFIG_FILE=... or map it into /app/... :)

Hope that helps!

**Comment by yagyeshgod** [comment]
1. pipx command saying its already at latest version

![Screenshot (251)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/11e68d7d-c51b-4ea8-9722-e4fdef20ec28)

2. Yes I was using with any arguments. Using environment variable successfully worked. Thanks

![Screenshot (253)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/2d5a3f6d-4413-4d76-a7b8-e509cdd092ea)

3. Last thing I need to know is How to map config file as I want  to use this for multiple accounts?? I am beginner so do not have knowlege of mapping.. 

Tool is amazing . Thanks for helping.

**Comment by atomicptr** [comment]
1. Huh, thats odd, can you try uninstalling/reinstalling it?
2. :+1: 
3.

```bash
$ docker run --rm -v hoyo-daily-logins-helper.toml:/app/hoyo-daily-logins-helper.toml ghcr.io/atomicptr/hoyo-daily-logins-helper:latest
```

Notice the **-v hoyo-daily-logins-helper.toml:/app/hoyo-daily-logins-helper.toml** part, we're mapping the local file into the container under /app/...

**Comment by yagyeshgod** [comment]
1. Tried uninstalling/reinstalling via pipx. Same version is gettings installed. Attaching image for reference

![Screenshot (258)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/8d0f0498-e37a-441b-b2bc-04d7450a4200)

2. Still not able to figure out config file. Below are used commands and address of local file used.

![Screenshot (259)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/d37d76c9-8510-4ce9-87b1-764a6c6b5c04)
![Screenshot (264)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/b640a516-9f58-4a66-9483-a8626edb835d)
![Screenshot (263)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/ab7f651c-4a46-4827-a305-b3e0c4011c7b)
![Screenshot (260)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/8704e592-3b20-438b-821b-20337b06a09a)
![Screenshot (266)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/30e236b0-b613-4b0a-9eae-df9793cbdb98)

**Comment by atomicptr** [comment]
1. AH! I see why... I removed support for Python 3.10 at some point and 1.2.3 is probably the last version which ran on Python 3.10
2. I don't know if this is related to the Windows path (assuming that works) try adding a :Z at the end of the path aka -v path1:path2:Z and the second example seems super wrong considering it adds the file in a totally different location :)

**Comment by yagyeshgod** [comment]
Getting this error now 
Error response from daemon: invalid volume specification:

![Screenshot (268)](https://github.com/atomicptr/hoyo-daily-logins-helper/assets/12203929/b4913f63-c82a-4848-8aab-3ccc334d9a4e)

I hope I am not wasting ur time..😅

**Comment by atomicptr** [comment]
Well it doesn't like Windows paths as expected, maybe escaping them via c:\\\\users\\\\... helps? Isn't this WSL? In that case there should be some sort of alternative path available :thinking:

**Comment by yagyeshgod** [comment]
Thanks for helping
